electron-app/.erb/configs/webpack.config.main.prod.ts, electron-app/.erb/configs/webpack.config.renderer.dev.ts, electron-app/.erb/configs/webpack.config.renderer.prod.ts, electron-app/package.json, electron-app/pnpm-lock.yaml, electron-app/src/logger/logger.ts, electron-app/src/logger/mainLogger.ts
=> fix: logger not printed after packaged

build/set-version.sh, electron-app/.erb/configs/webpack.config.base.ts, electron-app/package.json, electron-app/release/app/package-lock.json, electron-app/release/app/package.json, electron-app/src/renderer/pages/about/about.tsx, electron-app/src/types/webpackInject.d.ts
이제 빌드 시 0.0.1 이 아닌, package.json 에 정의된 버전을 따라갑니다.
=> feature: apply package version to component / build items

electron-app/src/renderer/components/Progress.tsx, electron-app/src/renderer/pages/clusterManagement/clusterInfoList.tsx, electron-app/src/renderer/pages/clusterManagement/clusterMetadataStore.ts, electron-app/src/renderer/pages/clusterManagement/page.tsx, electron-app/src/renderer/pages/clusterManagement/progressSnackbar.tsx, electron-app/src/renderer/pages/clusterManagement/topBar.tsx
- add hard reload (trigger sync)
- add progress snackbar when fetch/sync cluster metadata
=> feature: add metadata request notification, add hard reload

backend/controller/kubeconfig_controller/controller.go, backend/pkg/raw_service/azure_service/azure_config.go, backend/pkg/service/cluster_metadata_service/azure.go, backend/pkg/service/cluster_metadata_service/fox.go, backend/pkg/service/cluster_metadata_service/service.go, backend/pkg/service/cluster_metadata_service/tencent.go, backend/pkg/service/cluster_register_service/service.go, backend/pkg/service/cred_resolver_service/resolve_service.go, backend/pkg/types/enums.go
Enhancement codes
1. Do not use gRPC error code, instead use user defined error code.
- gRPC error means, doesn't expected error 
2. Change SyncAvailableClusters use goroutines
=> Refactor codes

electron-app/package.json, electron-app/pnpm-lock.yaml, electron-app/src/main/main.ts, electron-app/src/renderer/App.tsx, electron-app/src/renderer/components/clusterRegisterRequester.ts, electron-app/src/renderer/components/notiSnackbar.tsx, electron-app/src/renderer/components/registerErrorToNoti.tsx, electron-app/src/renderer/pages/clusterManagement/page.tsx, electron-app/src/renderer/store/eventStore.ts, electron-app/src/renderer/store/snackbarStore.ts
register request 가 실패할 경우 에러를 표시합니다
=> feature: register failed notification

.github/workflows/build.yaml, .github/workflows/pr_test.yaml, build/set-version.sh, electron-app/package.json, electron-app/release/app/package-lock.json, electron-app/release/app/package.json
Features
1. add mac universal package
2. change parallel build
=> feat: add mac universal package

electron-app/.vscode/launch.json, electron-app/package.json
- vscode 에서 renderer 디버깅을 할 수 있도록 launch option 을 추가합니다.
=> feature: add renderer debugging option

electron-app/src/renderer/repositories/clusterRepository.ts, electron-app/src/renderer/store/clusterRegisterStore.ts
payload 가 반환되지 않아 등록이 되지 않는 버그를 수정합니다.
=> fix: resposne not returned from repository layer

electron-app/src/renderer/pages/credResolver/page.tsx
cred resolver config 페이지에서 로딩 도중에 add button 이 보이지 않도록 수정합니다.
=> fix: hide add button when loading

electron-app/src/renderer/pages/about/about.tsx
=> Update About Page Year

electron-app/package.json, electron-app/release/app/package-lock.json, electron-app/release/app/package.json
=> set version to 0.2.0

electron-app/src/main/main.ts, electron-app/src/renderer/pages/clusterManagement/regStatusModal/index.tsx, electron-app/src/renderer/pages/clusterManagement/topBar.tsx
- make full size (not fullscreen) on startup
- focus on startup
- show registered clusters as default
- fix register status modal closed even if it's not finished yet
=> feature: UI update

electron-app/src/renderer/store/profileStore.ts
fetch each vendor's profile in parallel
=> feature: fetch vendor profile parallel

electron-app/src/renderer/pages/clusterManagement/bottomBar.tsx, electron-app/src/renderer/pages/clusterManagement/clusterList/columnFactory.tsx, electron-app/src/renderer/pages/configuration/configuration.tsx
- add vendor icon on cluster registeration page
- change button text "register all" to "register selected"
- fix setting page layout
=> feature: improve UI

electron-app/src/renderer/pages/clusterManagement/regStatusModal/index.tsx, electron-app/src/renderer/store/clusterRegisterStore.ts, electron-app/src/renderer/types/cancellationToken.ts
- now user can cancel process during registeration
=> feature: add register cancellation

electron-app/package.json, electron-app/release/app/package-lock.json, electron-app/release/app/package.json
=> Update App Version to 0.2.6

backend/application/application.go, backend/pkg/common/common.go, backend/pkg/raw_service/aws_service/register.go, backend/pkg/raw_service/azure_service/register.go, backend/pkg/raw_service/gcp_service/register.go
CLI실행을 fatal없이 안전하게 실행하도록 합니다.
=> Fix execute to safety

electron-app/package.json, electron-app/pnpm-lock.yaml, electron-app/src/main/backend/backend.ts
fix `macos` $PATH not imported from shell
=> feature: macos path fix

electron-app/src/main/logger/mainLogger.ts, electron-app/src/main/preload.js
main.log, renderer.log 을 새 인스턴스를 킬 때 마다 rotate 합니다.
=> feature: log rotating

backend/controller/kubeconfig_controller/controller.go, backend/pkg/raw_service/kubeconfig_service/service.go
=> Fix Delte Cluster RPC [ci skip]

electron-app/package.json, electron-app/release/app/package-lock.json, electron-app/release/app/package.json
=> update version to 0.3.0

electron-app/package.json, electron-app/release/app/package-lock.json, electron-app/release/app/package.json, electron-app/src/renderer/pages/configuration/page.tsx
- app config 디렉토리를 여는 링크와, logs 디렉토리를 여는 링크가 반대로 걸려있는 것을 수정합니다.
- 버전을 0.3.1 으로 올립니다.
=> fix: open dir wrong link

.githooks/pre-commit, .github/workflows/build.yaml, backend/pkg/concurrency/concurrency.go, backend/pkg/service/cluster_metadata_service/azure/resolver.go, backend/pkg/service/cluster_metadata_service/azure/resolver_test.go, backend/pkg/service/cluster_metadata_service/service.go
azure metadata resolver가 무한루프 돌던 문제를 해결합니다.
=> Fix azure metadata resolver infinite loop
